apiVersion: v1
data:
  config.toml: |-
    [chain]
    assert_chain_id = "simpleTestChain"
    major_version = 0
    minor_version = 17
    genesis_file = "genesis.json"
      [chain.consensus]
      name = "tendermint"
      major_version = 0
      minor_version = 8
      relative_root = "tendermint"
      [chain.manager]
      name = "burrowmint"
      major_version = 0
      minor_version = 17
      relative_root = "burrowmint"
    [servers]
      [servers.bind]
      address = ""
      port = 1337
      [servers.tls]
      tls = false
      cert_path = ""
      key_path = ""
      [servers.cors]
      enable = false
      allow_origins = []
      allow_credentials = false
      allow_methods = []
      allow_headers = []
      expose_headers = []
      max_age = 0
      [servers.http]
      json_rpc_endpoint = "/rpc"
      [servers.websocket]
      endpoint = "/socketrpc"
      max_sessions = 50
      read_buffer_size = 4096
      write_buffer_size = 4096
      [servers.tendermint]
      rpc_local_address = "0.0.0.0:46657"
      endpoint = "/websocket"
      [servers.logging]
      console_log_level = "info"
      file_log_level = "warn"
      log_file = "burrow-logs.log"
    [tendermint]
    private_validator_file = "priv_validator.json"
      [tendermint.configuration]
      moniker = "myOrg-simpleTestChain-validator-000"
      seeds = "burrow-peer-000:46656"
      fast_sync = true
      db_backend = "leveldb"
      log_level = "info"
      node_laddr = "tcp://0.0.0.0:46656"
      rpc_laddr = "tcp://0.0.0.0:46657"
      proxy_app = "tcp://127.0.0.1:46658"
        [tendermint.configuration.p2p]
        dial_timeout_seconds = 1
        handshake_timeout_seconds = 5
        max_num_peers = 20
        authenticated_encryption = true
        send_rate = 512000
        recv_rate = 512000
        fuzz_enable = false # use the fuzz wrapped conn
        fuzz_active = false # toggle fuzzing
        fuzz_mode = "drop"  # eg. drop, delay
        fuzz_max_delay_milliseconds = 3000
        fuzz_prob_drop_rw = 0.2
        fuzz_prob_drop_conn = 0.00
        fuzz_prob_sleep = 0.00
    [burrowmint]
    db_backend = "leveldb"
    tendermint_host = "0.0.0.0:46657"
    [logging]
      [logging.root_sink]
        [logging.root_sink.transform]
          transform_type = "filter"
          filter_mode = "exclude_when_all_match"
          [[logging.root_sink.transform.predicates]]
            key_regex = "log_channel"
            value_regex = "Trace"
        [[logging.root_sink.sinks]]
          [logging.root_sink.sinks.output]
            output_type = "stderr"
            format = "json"
kind: ConfigMap
metadata:
  labels:
    app: burrow
    chart: burrow-0.4.5
    heritage: Tiller
    release: burrow
  name: burrow-config-000
---
apiVersion: v1
data:
  genesis.json: null
kind: Secret
metadata:
  labels:
    app: burrow
    chart: burrow-0.4.5
    heritage: Tiller
    release: test-burrow
  name: burrow-genesis
type: Opaque
---
apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app: burrow
    chart: burrow-0.4.5
    heritage: Tiller
    release: burrow
  name: burrow-keys
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: burrow
    chart: burrow-0.4.5
    heritage: Tiller
    release: burrow
  name: burrow-api
spec:
  ports:
  - name: api
    port: 1337
    protocol: TCP
    targetPort: api
  selector:
    app: burrow
    release: burrow
  sessionAffinity: ClientIP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: burrow
    chart: burrow-0.4.5
    heritage: Tiller
    nodeNumber: "000"
    release: burrow
  name: burrow-peer-000
spec:
  ports:
  - name: peer
    port: 46656
    protocol: TCP
    targetPort: peer
  selector:
    app: burrow
    nodeNumber: "000"
    release: burrow
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: burrow
    chart: burrow-0.4.5
    heritage: Tiller
    release: burrow
  name: burrow-rpc
spec:
  ports:
  - name: rpc
    port: 46657
    protocol: TCP
    targetPort: rpc
  selector:
    app: burrow
    nodeNumber: "000"
    release: burrow
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: burrow
    chart: burrow-0.4.5
    heritage: Tiller
    release: burrow
  name: burrow-000
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: burrow
        nodeNumber: "000"
        release: burrow
    spec:
      containers:
      - args: null
        env:
        - name: BURROW_WORKDIR
          value: /work
        - name: BURROW_DATADIR
          value: /data
        image: quay.io/monax/db:0.17.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /status
            port: rpc
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 1
        name: node-000
        ports:
        - containerPort: 46656
          name: peer
          protocol: TCP
        - containerPort: 46657
          name: rpc
          protocol: TCP
        - containerPort: 1337
          name: api
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status
            port: rpc
            scheme: HTTP
          initialDelaySeconds: 1
        volumeMounts:
        - mountPath: /work
          name: work-dir
        - mountPath: /data
          name: data-dir
      initContainers:
      - command:
        - sh
        - -xc
        - echo Initializing...; sleep 0; echo Ready to go!
        image: busybox
        imagePullPolicy: IfNotPresent
        name: init-node
      - command:
        - sh
        - -xc
        - cp /ref/config.toml /work/; cp /ref/genesis.json /work/; cp /ref/priv_validator.json
          /work/
        image: busybox
        imagePullPolicy: IfNotPresent
        name: init-dir
        volumeMounts:
        - mountPath: /work
          name: work-dir
        - mountPath: /ref
          name: ref-dir
      securityContext:
        fsGroup: 101
        runAsUser: 1000
      tolerations: []
      volumes:
      - name: ref-dir
        projected:
          sources:
          - configMap:
              items:
              - key: config.toml
                path: config.toml
              name: burrow-config-000
          - secret:
              items:
              - key: genesis.json
                path: genesis.json
              name: burrow-genesis
          - secret:
              items:
              - key: key-000
                path: priv_validator.json
              name: burrow-keys
      - emptyDir: {}
        name: work-dir
      - emptyDir: {}
        name: data-dir
